### ISSUE TITLE
Problems with xesmf import after offline migration conda environment

### ISSUE THREAD

**Issue by cccchou** [JiaweiZhuang/xESMF#141]
After migrating my conda environment offline(using conda pack), on the new platform, I get an error importing xesmf:
Traceback (most recent call last).
  File "/home/gusf/miniconda3/envs/nc2p/lib/python3.11/site-packages/esmpy/interface/loadESMF.py", line 144, in <module>
    _ESMF = ct.CDLL(os.path.join(libsdir,'libesmf_fullylinked.so'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gusf/miniconda3/envs/nc2p/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /home/conda/feedstock_root/build_artifacts/esmf_1677849384616/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_ placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold placeh/lib/libesmf_fullylinked.so: cannot open shared object file: No such file or directory
Traceback (most recent call last).
  File "/home/gusf/miniconda3/envs/nc2p/lib/python3.11/site-packages/esmpy/interface/loadESMF.py", line 144, in <module>
    _ESMF = ct.CDLL(os.path.join(libsdir,'libesmf_fullylinked.so'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gusf/miniconda3/envs/nc2p/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /home/conda/feedstock_root/build_artifacts/esmf_1677849384616/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_ placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold placeh/lib/libesmf_fullylinked.so: cannot open shared object file: No such file or directory

I know this is caused by a problem with the OS path after migrating the environment, so how do I change the LINK path? I have successfully deployed ESMF on the new platform.

**Comment by cccchou** [comment]
My libesmf_fullylinked.so is in /home/gusf/miniconda3/envs/nc2p/lib/libesmf_fullylinked.so in python and /home/gusf/zzp/esmf-8.6.0/lib/libO/Linux.intel.64.mpiuni.default in ESMF
